source 'https://github.com/CocoaPods/Specs.git'
source 'git@coding.jiamiantech.com:ce/LRSDevRepo/LRSRepos.git'

use_frameworks!
platform :ios, '11.0'

target 'LRSMessageToolBar_Example' do
  
  pod 'LRSMessageToolBarComponents', :path => '../', :modular_headers => true
  pod 'SnapKit'
end
